config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"musics#index"
  resources :users, only: [:show] do
    resources :relationships, only: [:create, :destroy]
    # お気に入りの音楽一覧ページへのルート
    get 'favorites', to: 'users#favorites'
  end

  resources :musics do
    #originalsアクションへのルートを追加
    collection do
      get 'originals', to: 'musics#originals' 
    end
    resources :comments, only: :create
    #音楽投稿内容が存在しないとルートが発生しない為、musicsにネスト
    resources :likes, only: [:create, :destroy]
  end

  resources :genres, only: [:index, :show]

  resources :years, only: [:index, :show]

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :music
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_music
  def create
    like = current_user.likes.build(music_id: params[:music_id])
    like.save
    render partial: 'likes/like', locals: { music: @music }
  end

  def destroy
    like = current_user.likes.find_by(music_id: @music.id)
    like.destroy
    render partial: 'likes/like', locals: { music: @music }
  end

  private

  def set_music
    @music = Music.find(params[:music_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<!-- いいねボタン -->
<%= turbo_frame_tag dom_id(music, :like) do %>
  <% if user_signed_in? && @music.liked_by?(current_user) %>
    <% like = current_user.likes.find_by(music_id: music.id) %>
    <%= link_to "いいね済♪", music_like_path(music_id: @music.id, id: like.id), data: { turbo_method: :delete }, class: "like-button liked" %>
  <% else %>
    <%= link_to "いいね♪", music_likes_path(@music.id), data: { turbo_method: :post }, class: "like-button"%>
  <% end %>
 <% end %>

app/views/likes/create.js.erb
document.getElementById('like-btn<%= @music.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {music: @music}) %>"

app/views/likes/destroy.js.erb
document.getElementById('like-btn<%= @music.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {music: @music}) %>"