config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"musics#index"
  resources :users, only: [:show] do
    resources :relationships, only: [:create, :destroy]
    # お気に入りの音楽一覧ページへのルート
    get 'favorites', to: 'users#favorites'
  end

  resources :musics do
    #originalsアクションへのルートを追加
    collection do
      get 'originals', to: 'musics#originals' 
    end
    resources :comments, only: :create
    #音楽投稿内容が存在しないとルートが発生しない為、musicsにネスト
    resources :likes, only: [:create, :destroy]
  end

  resources :genres, only: [:index, :show]

  resources :years, only: [:index, :show]

end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<!-- FOOTER -->
<footer class="container">
  <p class="float-end"><a href="#">Back to top</a></p>
  <p class="btn btn-outline-danger">&copy; 2023–2023 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
</footer>

app/views/shared/_header.html.erb
<header data-bs-theme="dark">
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <%= link_to 'from8bit', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to current_user.nickname, user_path(current_user), class: "user-nickname nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: "logout nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'ログイン', new_user_session_path, class: "login nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to '新規登録', new_user_registration_path, class: "sign-up nav-link" %>
            </li>
          <% end %>
        </ul>
        <%= search_form_for @search, url: musics_path, html: { method: :get, class: "d-flex" } do |f| %>
          <%= f.search_field :title_or_description_or_game_name_cont, placeholder: "Search", aria: { label: "Search" }, class: "form-control me-2" %>
          <%= f.submit "Search", class: "btn btn-outline-success" %>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_second_header.html.erb
<div id="myCarousel" class="carousel slide mb-6" data-bs-ride="carousel" data-bs-theme="light">
   <div class="carousel-indicators">
    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <svg class="bd-placeholder-img" width="100%" height="50" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>
      <div class="container">
        <div class="carousel-caption">
          <%= link_to "ゲーム音楽を投稿する<br>[Post game music]".html_safe, new_music_path, class: "btn btn-outline-light" %>
        </div>
        <%= image_tag("oto_banner.jpg", class:"img-thumbnail") %>
      </div>
    </div>
    <div class="carousel-item">
      <svg class="bd-placeholder-img" width="100%" height="50" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>
      <div class="container">
        <div class="carousel-caption">
          <% if current_user %>
            <p><%= link_to "マイページ<br>[MyPage]".html_safe, user_path(current_user), class: 'btn btn-outline-light' %></p>
          <% else %>
            <p><%= link_to "ログイン<br>[Login]".html_safe, new_user_session_path, class: 'btn btn-outline-light' %></p>
          <% end %>
        </div>
        <%= image_tag("music_banner.jpg", class:"img-thumbnail") %>
    </div>
  </div>
    <div class="carousel-item">
      <svg class="bd-placeholder-img" width="100%" height="50" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>
      <div class="container">
        <%= image_tag("iine_banner.jpg", class:"img-thumbnail") %>
        <div class="carousel-caption">
          <!-- お気に入りの音楽一覧ページへのリンク -->
          <% if current_user %>
            <p><%= link_to "お気に入りの音楽<br>[Favorite music]".html_safe, user_favorites_path(current_user), class: 'btn btn-outline-light' %></p>
          <% else %>
            <p>アカウントを作成して、お気に入りの音楽を保存しましょう！<br>
            <%= link_to "サインアップ<br>[Sign Up]".html_safe, new_user_registration_path, class: 'btn btn-outline-light' %></p>
          <% end %>
        </div>
        </div>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_user_header.html.erb
<header data-bs-theme="dark">
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">from8bit</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    </div>
  </nav>
</header>