config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"musics#index"
  resources :users, only: [:show] do
    resources :relationships, only: [:create, :destroy]
    # お気に入りの音楽一覧ページへのルート
    get 'favorites', to: 'users#favorites'
  end

  resources :musics do
    #originalsアクションへのルートを追加
    collection do
      get 'originals', to: 'musics#originals' 
    end
    resources :comments, only: :create
    #音楽投稿内容が存在しないとルートが発生しない為、musicsにネスト
    resources :likes, only: [:create, :destroy]
  end

  resources :genres, only: [:index, :show]

  resources :years, only: [:index, :show]

end

app/models/music.rb
class Music < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :user
  has_one_attached :image
  has_one_attached :music_file
  has_many :comments, dependent: :destroy
  belongs_to :genre
  belongs_to :year
  has_many :likes, dependent: :destroy

  validates :user, presence: { message: 'ユーザーを選択してください' }
  validates :image, presence: { message: '画像を選択してください' }
  validates :title, presence: { message: 'タイトルを入力してください' }
  validates :description, presence: { message: '説明を入力してください' }
  validates :music_file, presence: { message: '音楽ファイルを選択してください' }
  validates :year_id, presence: { message: '年代を選択してください' }
  validates :genre_id, presence: { message: 'ジャンルを選択してください' }

  # 選択が「--」の時(1の時)は保存不可のバリデーション
  validates :year_id, numericality: { other_than: 1, message: '年代を選択してください' }
  validates :genre_id, numericality: { other_than: 1, message: 'ジャンルを選択してください' }

  validate :music_file_content_type, if: -> { music_file.attached? }

  def description_with_links
    # description フィールド内のURLをリンクに変換するロジックを実装
    description.gsub(URI::DEFAULT_PARSER.make_regexp, '<a href="\0">\0</a>').html_safe
  end

  # いいね済みか否か判定
  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def self.ransackable_attributes(_auth_object = nil)
    # 検索を許可する属性のリスト
    %w[title description game_name]
  end

  # 検索可能な関連付けを定義する
  def self.ransackable_associations(_auth_object = nil)
    # 検索可能な関連付けの名前を記述
    %w[comments user]
  end

  # カスタムのransackスコープを追加
  def self.ransackable_scopes(_auth_object = nil)
    [:search__id_as_text]
  end

  # idをテキストとして検索するためのスコープ
  def self.search__id_as_text(query)
    where('cast(year_id as text) LIKE :query OR cast(genre_id as text) LIKE :query', query: "%#{query}%")
  end

  private

  def music_file_content_type
    acceptable_types = ['audio/mp3', 'audio/mpeg', 'audio/wav']
    return if acceptable_types.include?(music_file.content_type)

    errors.add(:music_file, 'はMP3またはWAVファイルである必要があります')
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  # ログアウト状態のユーザーが投稿ページへ遷移を試みると、ログインページへリダイレクトするよう設定
  before_action :authenticate_user!, except: [:index]
  before_action :set_music, only: [:show, :edit, :update, :destroy]

  def index
    # 検索オブジェクトの作成（検索を試みた場合先に実行される）
    @search = Music.ransack(params[:q])
    @musics = if params[:q].present?
                @search.result(distinct: true).includes(:user).order('created_at DESC')
              else
                Music.includes(:user).order('created_at DESC')
              end
  end

  def new
    @music = Music.new
  end

  def create
    @music = Music.new(music_params.merge(user_id: current_user.id))

    if @music.save
      redirect_to root_path
    else
      puts 'Validation errors:'
      puts @music.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @comment = Comment.new
    @comments = @music.comments.includes(:user).order(created_at: :desc)
  end

  def edit
    # ログインしているユーザー且つ編集ページのユーザーと一致していればeditファイルが読み込まれる
    return if @music.user_id == current_user.id

    redirect_to root_path
  end

  def update
    if @music.update(music_params)
      redirect_to music_path(@music)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # ログイン状態のユーザーと一致している場合削除
    @music.destroy if @music.user_id == current_user.id
    redirect_to root_path
  end

  def originals
    original_genre = Genre.find_by(name: 'オリジナル楽曲(original_music)')
    @original_musics = original_genre.musics
  end

  def music_params
    params.require(:music).permit(:game_name, :title, :description, :music_file, :year_id, :genre_id, :target, :image)
  end

  def set_music
    @music = Music.find(params[:id])
  end
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/musics/edit.html.erb
<%= stylesheet_link_tag 'musics' %>
<%= render "shared/header" %>
<%= render "shared/second_header" %>

<div class="container music-container mt-4">
  <h1 class="music-title text-center mb-4">♪ゲーム音楽編集</h1>
  

  <%= form_with(model: @music, data: { turbo: false }, local: true, class: 'shadow p-4 rounded bg-white') do |f| %>
    
    <%# インスタンスを渡して、エラー発生時にメッセージを表示。%>
    <%= render partial: "shared/error_messages", locals: { model: @music } %>

    <div class="input-field mb-3">
      <%= f.label :image, "画像投稿" %>
      <%= f.file_field :image, class: 'form-control' %>
    </div>

    <div class="input-field mb-3">
      <%= f.label :game_name, "ゲーム名" %>
      <%= f.text_field :game_name, class: 'form-control' %>
    </div>

    <div class="input-field mb-3">
      <%= f.label :title, "曲のタイトル" %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="input-field mb-3">
      <%= f.label :description, "説明" %>
      <%= f.text_area :description, class: 'form-control', rows: '5', placeholder: '※音楽についての説明や外部ファイルの場合URLを記入して下さい' %>
    </div>

    <div class="input-field mb-3">
      <%= f.label :music_file, "音楽ファイル" %>
      <%= f.file_field :music_file, class: 'form-control' %>
    </div>

    <div class="input-field mb-3">
      <%= f.label :year_id, "年代" %>
      <%= f.select :year_id, Year.data.map { |y| [y[:name], y[:id]] }, {}, class: 'form-control' %>
    </div>

    <div class="input-field mb-3">
      <%= f.label :genre_id, "ジャンル" %>
      <%= f.collection_select :genre_id, Genre.all, :id, :name, {include_blank: "---"}, class: 'form-control' %>
    </div>

    <div class="input-field mb-3">
      <%= f.label :target, "対象" %>
      <%= f.text_area :target, class: 'form-control', rows: '5', placeholder: '※任意(どんな状況の人に聞いて欲しいか、是非教えて下さい！)' %>
    </div>

    <%= f.submit "更新する", class: "submit-btn btn btn-primary btn-block mt-3" %>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/musics/index.html.erb
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.112.5">
    <title>Carousel Template · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/carousel/">


    

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }



    </style>

    
    <!-- Custom styles for this template -->
    
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>

    
<%= render "shared/header" %>
<%= render "shared/second_header" %>

<main>

 


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing">

    <div class="text-center">
      <br>
      <div class="container">
       </div>
      <h2>あなたが好きなゲーム音楽を共有し、新しいお気に入りに出会える場所</h2>
     【Share the game music you adore; discover tunes you'll fall in love with.】
    </div>
    <br>

    <div class="row">
      <div class="col-lg-4">
        <%= image_tag("game1980.jpg", class:"img-thumbnail") %>
        <h2 class="fw-normal">年代別ゲーム音楽</h2>
        <p>1980年代〜2020年代までの音楽を年代毎に検索できます。懐かしい音楽や最新のゲーム音楽を探してみましょう。</p>
        <p><%= link_to 'listen to music &raquo;'.html_safe, years_path, class: 'btn btn-outline-danger' %></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <%= image_tag("game_shop.png", class:"img-thumbnail") %>
        <h2 class="fw-normal">ジャンル別ゲーム音楽</h2>
        <p>アクションやRPGなどジャンル毎で探したい方はこちらから検索できます。</p>
         <p><%= link_to 'listen to music &raquo;'.html_safe, genres_path, class: 'btn btn-outline-info' %> </p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <%= image_tag("geisha.png", class:"img-thumbnail") %>
        <h2 class="fw-normal" >オリジナル楽曲</h2>
        <p>皆さんが投稿した、〇〇風音楽やお気に入りのゲームへ向けたオリジナル楽曲を見つけてみましょう。</p>
        <p><%= link_to 'listen to music &raquo;'.html_safe, originals_musics_path, class: 'btn btn-outline-secondary'%></p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

  <hr class="featurette-divider">

  <div class="container music-container mt-4">

  <% @musics.each_with_index do |music, index| %>

    <hr class="featurette-divider">

    <div class="row featurette">
      <% if index.even? %>
        <div class="col-md-7">
          <h2  class="fw-semibold"><%= music.game_name %> - <%= music.title %></h2>
          <p class="text-bg-light p-3"><%= music.description_with_links %></p> <!-- description_with_links を呼び出す -->

          <ul class="Medium weight text.">
            <li><strong>User:</strong> <%= link_to music.user.nickname, music_path(music) if music.user %></li>
            <li><strong>年代（Year）:</strong> <%= music.year.name if music.year %></li>
            <li><strong>ジャンル（Genre）:</strong> <%= music.genre.name if music.genre %></li>
            <li><strong>対象（Target）:</strong> <%= music.target if music.target %></li>
            <li><strong>Music File:</strong> 
              <% if music.music_file.attached? %>
                <div >
                  <%= audio_tag rails_blob_path(music.music_file), controls: true %>
                </div>
              <% else %>
                Not Attached
              <% end %>
            </li>
          </ul>
        </div>
        <div class="col-md-5">
           <%= link_to(image_tag(music.image.variant(resize: '500x500'), class: "featurette-image img-fluid mx-auto"), music_path(music)) if music.image.attached? %>
        </div>
      <% else %>
        <div class="col-md-7 order-md-2">
          <h2 class="fw-semibold"><%= music.game_name %> - <%= music.title %></h2>
          <p class="text-bg-light p-3"><%= music.description_with_links %></p> <!-- description_with_links を呼び出す -->
          
          <!-- Music Details based on validation columns -->
          <ul class="Medium weight text.">
            <li><strong>User:</strong> <%= link_to music.user.nickname, music_path(music) if music.user %></li>
            <li><strong class="">年代（Year）:</strong> <%= music.year.name if music.year %></li>
            <li><strong>ジャンル（Genre）:</strong> <%= music.genre.name if music.genre %></li>
            <li><strong>対象（Target）:</strong> <%= music.target if music.target %></li>
            <li><strong>Music File:</strong> 
              <% if music.music_file.attached? %>
                <div >
                  <%= audio_tag rails_blob_path(music.music_file), controls: true %>
                </div>
              <% else %>
                Not Attached
              <% end %>
            </li>
          </ul>
        </div>
        <div class="col-md-5 order-md-1">
           <%= link_to(image_tag(music.image.variant(resize: '500x500'), class: "featurette-image img-fluid mx-auto"), music_path(music)) if music.image.attached? %>
        </div>
      <% end %>
    </div>

  <% end %>
</div>


<hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->

<%= render "shared/footer" %>

app/views/musics/new.html.erb
<%= stylesheet_link_tag 'musics' %>
<%= render "shared/header" %>
<%= render "shared/second_header" %>

<div class="container music-container mt-4">
  <h1 class="music-title text-center mb-4">♪ゲーム音楽投稿</h1>
  

  <%= form_with(model: @music, data: { turbo: false }, local: true, class: 'shadow p-4 rounded bg-white') do |f| %>
    
    <%# インスタンスを渡して、エラー発生時にメッセージを表示。%>
    <%= render partial: "shared/error_messages", locals: { model: @music } %>

    <div class="input-field mb-3">
      <%= f.label :image, "画像投稿" %>
      <%= f.file_field :image, class: 'form-control' %>
    </div>

    <div class="input-field mb-3">
      <%= f.label :game_name, "ゲーム名" %>
      <%= f.text_field :game_name, class: 'form-control' %>
    </div>

    <div class="input-field mb-3">
      <%= f.label :title, "曲のタイトル" %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="input-field mb-3">
      <%= f.label :description, "説明" %>
      <%= f.text_area :description, class: 'form-control', rows: '5', placeholder: '※音楽についての説明や外部ファイルの場合URLを記入して下さい' %>
    </div>

    <div class="input-field mb-3">
      <%= f.label :music_file, "音楽ファイル" %>
      <%= f.file_field :music_file, class: 'form-control' %>
    </div>

    <div class="input-field mb-3">
      <%= f.label :year_id, "年代" %>
      <%= f.select :year_id, Year.data.map { |y| [y[:name], y[:id]] }, {}, class: 'form-control' %>
    </div>

    <div class="input-field mb-3">
      <%= f.label :genre_id, "ジャンル" %>
      <%= f.collection_select :genre_id, Genre.all, :id, :name, {include_blank: "---"}, class: 'form-control' %>
    </div>

    <div class="input-field mb-3">
      <%= f.label :target, "対象" %>
      <%= f.text_area :target, class: 'form-control', rows: '5', placeholder: '※任意(どんな状況の人に聞いて欲しいか、是非教えて下さい！)' %>
    </div>

    <%= f.submit "投稿する", class: "submit-btn btn btn-primary btn-block mt-3" %>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/musics/originals.html.erb
<%= stylesheet_link_tag 'original_music' %>
<%= render "shared/header" %>
<%= render "shared/second_header" %>

<div class="container mt-5">
  <h1 class="text-center mb-4 display-4">オリジナル楽曲一覧</h1>

  <% @original_musics.each_with_index do |music, index| %>
    <div class="row featurette mb-5">
      <div class="col-md-7 mt-3">
        <h2 class="display-5"><%= music.game_name %> - <%= music.title %></h2>
        <p class="lead bg-light p-3 rounded"><%= music.description_with_links %></p>
        <ul class="list-unstyled mt-3">
          <li><strong>User:</strong> <%= link_to music.user.nickname, music_path(music) if music.user %></li>
          <li><strong>年代（Year）:</strong> <%= music.year.name if music.year %></li>
          <li><strong>ジャンル（Genre）:</strong> <%= music.genre.name if music.genre %></li>
          <li><strong>Music File:</strong> 
            <% if music.music_file.attached? %>
              <div>
                <%= audio_tag rails_blob_path(music.music_file), controls: true %>
              </div>
            <% else %>
              Not Attached
            <% end %>
          </li>
        </ul>
        <div class="mt-3">
          <%= link_to "詳細", music_path(music), class: "btn btn-outline-primary" %>
        </div>
      </div>
      <div class="col-md-5">
        <%= link_to(image_tag(music.image.variant(resize: '500x500'), class: "img-thumbnail"), music_path(music)) if music.image.attached? %>
      </div>
    </div>
    <hr class="featurette-divider">
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/musics/show.html.erb
<%= render "shared/header" %>
<%= stylesheet_link_tag 'show' %>
<br>
<br>
<br>

<div class="container">
  <!-- タイトルとゲーム名を追加 -->
  <h2 class="text-center mt-3"><%= @music.game_name %> - <%= @music.title %></h2> 
  <div class="music-details">
    <% if @music.image.attached? %>
      <div class="music-image">
        <%= link_to(image_tag(@music.image.variant(resize: '500x500'), class: "featurette-image img-fluid mx-auto"), music_path(@music)) %>
      </div>
    <% end %>
    <div class="music-audio">
      <% if @music.music_file.attached? %>
        <div>
          <%= audio_tag rails_blob_path(@music.music_file), controls: true %>
        </div>
      <% else %>
        Not Attached
      <% end %>
    </div>
    <div class="music-info">
      <p><strong>User:</strong> <%= @music.user.nickname %>
        <% unless @music.user == current_user %>
          <% if @music.user.followed_by?(current_user) %>
            <%= button_to "フォロー中", user_relationship_path(@music.user.id), method: :delete, class: "follow-button followed", data: { turbo: false } %>
          <% else %>
            <%= button_to "フォローする", user_relationships_path(@music.user.id), class: "follow-button", method: :post, data: { turbo: false } %>
          <% end %>
        <% end %>
      </p>
      <p><strong>年代（Year）:</strong> <%= @music.year.name if @music.year %></p>
      <p><strong>ジャンル（Genre）:</strong> <%= @music.genre.name if @music.genre %></p>
      <p><strong>対象（Target）:</strong> <%= @music.target if @music.target %></p>
    </div>
    <div class="music-description">
      <p class="text-bg-light p-3"><%= @music.description_with_links %></p> <!-- description_with_links を呼び出す -->
    </div>
    
    <%= render partial: "likes/like", locals: { music: @music } %>

    <!-- ログイン状態で、自身の投稿の場合にのみ「編集」「削除」ボタンを表示 -->
    <% if user_signed_in? && current_user == @music.user %>
      <%= link_to '編集', edit_music_path(@music), class: 'btn btn-primary' %>
      <%= link_to '削除', music_path(@music), data: { turbo_method: :delete }, class: 'btn btn-danger' %>
    <% end %>

    <!-- コメント欄 -->
    <div class="comments">
      <h3>コメント</h3>
      <% if user_signed_in? %>
        <!-- ログイン状態の場合、コメントフォームを表示 -->
        <%= form_with(model: [@music, @comment], local: true) do |f| %>
          <%= f.text_area :text, placeholder: "コメントを入力してください" %>
          <%= f.submit "コメントする" %>
        <% end %>
      <% else %>
        <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
      <% end %>

      <!-- コメント一覧 -->
      <div class="comments-list">
        <h4>コメント一覧</h4>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, user_path(comment.user) %>:</strong>
            <%= comment.text %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>