config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"musics#index"
  resources :users, only: [:show] do
    resources :relationships, only: [:create, :destroy]
    # お気に入りの音楽一覧ページへのルート
    get 'favorites', to: 'users#favorites'
  end

  resources :musics do
    #originalsアクションへのルートを追加
    collection do
      get 'originals', to: 'musics#originals' 
    end
    resources :comments, only: :create
    #音楽投稿内容が存在しないとルートが発生しない為、musicsにネスト
    resources :likes, only: [:create, :destroy]
  end

  resources :genres, only: [:index, :show]

  resources :years, only: [:index, :show]

end

app/models/year.rb
class Year < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '1970年代', image_url: 'game1970.jpg' },
    { id: 3, name: '1980年代', image_url: 'game1980_2.jpg' },
    { id: 4, name: '1990年代', image_url: 'game1990.jpg' },
    { id: 5, name: '2000年代', image_url: 'game2000.jpg' },
    { id: 6, name: '2010年代', image_url: 'game2010.jpg' },
    { id: 7, name: '2020年代', image_url: 'game2020.jpg' },
    { id: 8, name: '不明(unknown)', image_url: 'unknown.jpg' }

  ]

  include ActiveHash::Associations
  has_many :musics
end

app/controllers/years_controller.rb
class YearsController < ApplicationController
  def index
    @years = Year.all.reject { |year| year.id == 1 }
  end

  def show
    @year = Year.find(params[:id])
    @musics = @year.musics
  end
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/years/index.html.erb
<%= stylesheet_link_tag 'years_index' %>
<%= render "shared/header" %>
<%= render "shared/second_header" %>

<div class="container mt-5">
  <h1 class="text-center mb-4">年代一覧</h1>
  <div class="row justify-content-center">
    <% @years.each do |year| %>
      <% next if year.id == 1 %> <!-- id 1の年代をスキップ -->
      <div class="col-md-4 mb-4">
        <div class="card h-100 shadow">
          <%= link_to year_path(year.id) do %>
            <%= image_tag year.image_url, class: "card-img-top", alt: year.name, style: "width: 100%; height: 300px; object-fit: cover;" if year.image_url.present? %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title text-center"><%= year.name %></h5>
          </div>
          <div class="card-footer">
            <%= link_to '詳細', year_path(year.id), class: 'btn btn-primary btn-block' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/years/show.html.erb
<%= stylesheet_link_tag 'years_show' %>
<%= render "shared/header" %>
<%= render "shared/second_header" %>

<div class="container mt-5">
  <h1 class="text-center mb-4 display-4"><%= @year.name %> 年代のゲーム音楽</h1>

  <% @musics.each_with_index do |music, index| %>
    <div class="row featurette mb-5">
      <% if index.even? %>
        <div class="col-md-7 mt-3">
          <h2 class="display-5"><%= music.game_name %> - <%= music.title %></h2>
          <p class="lead bg-light p-3 rounded"><%= music.description_with_links %></p>
          <ul class="list-unstyled mt-3">
            <li><strong>User:</strong> <%= link_to music.user.nickname, music_path(music) if music.user %></li>
            <li><strong>年代（Year）:</strong> <%= music.year.name if music.year %></li>
            <li><strong>ジャンル（Genre）:</strong> <%= music.genre.name if music.genre %></li>
            <li><strong>Music File:</strong> 
              <% if music.music_file.attached? %>
                <div>
                  <%= audio_tag rails_blob_path(music.music_file), controls: true %>
                </div>
              <% else %>
                Not Attached
              <% end %>
            </li>
          </ul>
          <div class="mt-3">
            <%= link_to "詳細", music_path(music), class: "btn btn-outline-primary" %>
          </div>
        </div>
        <div class="col-md-5">
          <%= link_to(image_tag(music.image.variant(resize: '500x500'), class: "img-thumbnail"), music_path(music)) if music.image.attached? %>
        </div>
      <% else %>
        <div class="col-md-7 order-md-2 mt-3">
          <h2 class="display-5"><%= music.game_name %> - <%= music.title %></h2>
          <p class="lead bg-light p-3 rounded"><%= music.description_with_links %></p>
          <ul class="list-unstyled mt-3">
            <li><strong>User:</strong> <%= link_to music.user.nickname, music_path(music) if music.user %></li>
            <li><strong>年代（Year）:</strong> <%= music.year.name if music.year %></li>
            <li><strong>ジャンル（Genre）:</strong> <%= music.genre.name if music.genre %></li>
            <li><strong>Music File:</strong> 
              <% if music.music_file.attached? %>
                <div>
                  <%= audio_tag rails_blob_path(music.music_file), controls: true %>
                </div>
              <% else %>
                Not Attached
              <% end %>
            </li>
          </ul>
          <div class="mt-3">
            <%= link_to "詳細", music_path(music), class: "btn btn-outline-primary" %>
          </div>
        </div>
        <div class="col-md-5 order-md-1">
          <%= link_to(image_tag(music.image.variant(resize: '500x500'), class: "img-thumbnail"), music_path(music)) if music.image.attached? %>
        </div>
      <% end %>
    </div>
    <hr class="featurette-divider">
  <% end %>
</div>

<%= render "shared/footer" %>